services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  backend:
    build: ./server
    volumes:
    - ./server:/app
    ports:
    - "5000:5000"
    depends_on:
    - db
    environment:
    - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres


  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: